name: ImplodusPorts
main: me.NinjaMandalorian.ImplodusPorts.ImplodusPorts
version: 1.0.3
api-version: 1.19
description: Interactive port plugin for travelling across the world.
author: NinjaMandalorian, Xavbeat03
depend: [ Vault ]

commands:
  implodusports:
    description: Primary command
    softdepend: [ Vault ]
    aliases:
      - iports
  